version: '3.9'

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
#    environment:
#      PUID: 1000
#      PGID: 1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    # Add any other Stream port you want to expose
    # - '21:21' # FTP
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm

# proxy will point at fastapi:8888
  fastapi:
    image: myu/fastapi:latest
    container_name: myu_fastapi
    build:
      target: fastapi
    # I run the uvicorn fastapi app with --reload... in order for that to work,
    # I mount the app so uvicorn can see the updates to code and restart the app.
    # This way the app updates with my changes, and I do not need to launch docker :)
    volumes:
      - ./fastapp:/usr/src/api/fastapp
    networks:
      - npm

#  db:
#    image: myu/db:latest
#    container_name: myu_db
#    build:
#      target: db
#    networks:
#      - backend

# Create a network! Frontend network member "proxy" can get an api request from "fastapi" by pinging
# urls "http://myu_fastapi:8000" or "http://fastapi:8000" (The service name, or container_name. I will be using the container_name)
networks:
  npm:
    name: nginx_proxy_manager1
    driver: bridge
# bridge is a default network, I will be using it.
